<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    '2cffec82183ee1cea088009cef9a6fc3' => $vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
    'bf9f5270ae66ac6fa0290b4bf47867b7' => $vendorDir . '/adodb/adodb-php/adodb.inc.php',
    'decc78cc4436b1292c6c0d151b19445c' => $vendorDir . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    'b686b8e46447868025a15ce5d0cb2634' => $vendorDir . '/symfony/polyfill-php74/bootstrap.php',
    'a4a119a56e50fbb293281d9a48007e0e' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    'ccc52640a588dec7820c7d4737517ce9' => $vendorDir . '/totara/xhprof/xhprof_lib/utils/xhprof_lib.php',
    'b7c9591e9c2bf15a7ba5860541bbef95' => $vendorDir . '/totara/xhprof/xhprof_lib/utils/xhprof_runs.php',
    'd02bd9c37c1b329a04f3608a5eae65e2' => $vendorDir . '/totara/xhprof/xhprof_totara.php',
);
