<?php return array(
    'root' => array(
        'pretty_version' => 'dev-TL-34375/16',
        'version' => 'dev-TL-34375/16',
        'type' => 'metapackage',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'reference' => '9a24d9027dd315d1e6ada244d6a6ff17d2ce65bf',
        'name' => 'totara/totara_require',
        'dev' => true,
    ),
    'versions' => array(
        'adodb/adodb-php' => array(
            'pretty_version' => 'v5.21.2',
            'version' => '5.21.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../adodb/adodb-php',
            'aliases' => array(),
            'reference' => 'aa161c28dfffcab13a3cb9bd407917573987f0f6',
            'dev_requirement' => false,
        ),
        'box/spout' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../box/spout',
            'aliases' => array(),
            'reference' => '9bdb027d312b732515b884a341c0ad70372c6295',
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => '4c679186f2aca4ab6a0f1b0b9cf9252decb44d0b',
            'dev_requirement' => false,
        ),
        'defuse/php-encryption' => array(
            'pretty_version' => 'v2.3.1',
            'version' => '2.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../defuse/php-encryption',
            'aliases' => array(),
            'reference' => '77880488b9954b7884c25555c2a0ea9e7053f9d2',
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'reference' => '8768448244967a46d6e67b891d30878e0e15d25c',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.13.0',
            'version' => '4.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '08e27c97e4c6ed02f37c5b2b20488046c8d90d75',
            'dev_requirement' => false,
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'reference' => 'd01be5894a5c1a3381c58c9b1795cd07f96c30f7',
            'dev_requirement' => false,
        ),
        'goat1000/svggraph' => array(
            'pretty_version' => 'dev-totara-2.30.0',
            'version' => 'dev-totara-2.30.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../goat1000/svggraph',
            'aliases' => array(),
            'reference' => 'bcae0041e9e90de42c1881cabda28d2aedc031a6',
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => 'dev-totara-4.1.5',
            'version' => 'dev-totara-4.1.5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(
                0 => '9999999-dev',
                1 => '4.1.5',
            ),
            'reference' => 'dbf0bf17a0a6542293d1b712b097fcf45c56ab55',
            'dev_requirement' => false,
        ),
        'league/event' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/event',
            'aliases' => array(),
            'reference' => 'd2cc124cf9a3fab2bb4ff963307f60361ce4d119',
            'dev_requirement' => false,
        ),
        'league/oauth2-server' => array(
            'pretty_version' => '8.3.2',
            'version' => '8.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-server',
            'aliases' => array(),
            'reference' => '0809487d33dd8a2c8c8c04e4a599ba4aadba1ae6',
            'dev_requirement' => false,
        ),
        'league/oauth2server' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'lncd/oauth2' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.63',
            'version' => '1.3.63.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'reference' => '9ba1b459828adc13430f4dd6c49dae4950dc4117',
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'dev_requirement' => false,
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'reference' => 'b1f3c0699525336d09cc5161a2861268d9f2ae5b',
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.8.1',
            'version' => '0.8.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'reference' => '32f274051c543fc865e5a84d3a2c703913641ea8',
            'dev_requirement' => false,
        ),
        'michelf/php-markdown' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../michelf/php-markdown',
            'aliases' => array(),
            'reference' => 'c83178d49e372ca967d1a8c77ae4e051b3a3c75c',
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'dev_requirement' => false,
        ),
        'nyholm/psr7' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/psr7',
            'aliases' => array(),
            'reference' => '2212385b47153ea71b1c1b1374f8cb5e4f7892ec',
            'dev_requirement' => false,
        ),
        'opis/json-schema' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/json-schema',
            'aliases' => array(),
            'reference' => '39d8072be8657a329a284339994401066406c43b',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'dev_requirement' => false,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.2',
            'version' => '0.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'reference' => 'ca6ad461f032145fff5971b5985e5af9e7fa88d8',
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => 'v0.3.3',
            'version' => '0.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'reference' => '5fa61b65e612ce1ae15f69b3d223cb14ecc60e32',
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'dd803df5ad7492e1b40637f7ebd258fee5ca7355',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => 'a9ab55bfae02eecffb3df669a2e19ba0e2f04bbf',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.35',
            'version' => '2.0.35.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '4e16cf3f5f927a7d3f5317820af795c0366c0420',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.3.1',
            'version' => '8.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'reference' => 'd217848e1396ef962fb1997cf3e2421acba7f796',
            'dev_requirement' => false,
        ),
        'scssphp/scssphp' => array(
            'pretty_version' => 'dev-totara-1.0.5',
            'version' => 'dev-totara-1.0.5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scssphp/scssphp',
            'aliases' => array(),
            'reference' => '6aa228cf8224e9fc8f4bc9373bb9db3a119d78b0',
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'dev-totara-1.6.2',
            'version' => 'dev-totara-1.6.2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'reference' => '7d4194daba8698396e08d7bedb4b8fa2b3ef920a',
            'dev_requirement' => false,
        ),
        'simplepie/simplepie' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplepie/simplepie',
            'aliases' => array(),
            'reference' => '1c68e14ca3ac84346b6e6fe3c5eedf725d0f92c6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9174a3d80210dca8daa7f31fec659150bbeabfc6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php74' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php74',
            'aliases' => array(),
            'reference' => '577e147350331efeb816897e004d85e6e765daaf',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => 'dc3063ba22c2a1fd2f45ed856374d79114998f91',
            'dev_requirement' => false,
        ),
        'totara/totara_require' => array(
            'pretty_version' => 'dev-TL-34375/16',
            'version' => 'dev-TL-34375/16',
            'type' => 'metapackage',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'reference' => '9a24d9027dd315d1e6ada244d6a6ff17d2ce65bf',
            'dev_requirement' => false,
        ),
        'totara/xhprof' => array(
            'pretty_version' => 'dev-totara-2.3.5',
            'version' => 'dev-totara-2.3.5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../totara/xhprof',
            'aliases' => array(),
            'reference' => '6f9b50f8d7a60c27356dfa7fa8c58ac99d1a6212',
            'dev_requirement' => false,
        ),
        'webonyx/graphql-php' => array(
            'pretty_version' => 'v14.11.3',
            'version' => '14.11.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webonyx/graphql-php',
            'aliases' => array(),
            'reference' => 'a7192e7a2b0487dc5e185feb4f4df1fc24d35d86',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'dev_requirement' => false,
        ),
    ),
);
